name: notely
description: A new Flutter project.
publish_to: 'none'

version: 1.2.6+30
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
   
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  crypto: ^3.0.3
  shared_preferences: ^2.0.15
  google_mobile_ads:
    git:
      url: https://github.com/thilojaeggi/googleads-mobile-flutter.git
      path: packages/google_mobile_ads
      ref: main
  theme_provider: ^0.6.0
  fl_chart: ^1.1.1
  rename: ^2.0.1
  cupertino_native: ^0.1.1
  universal_io: ^2.3.1
  flutter_secure_storage: ^10.0.0
  home_widget: ^0.8.1
  page_transition: ^2.0.9
  package_info_plus: ^9.0.0
  variable_blur: ^0.1.0
  fl_toast: ^3.1.0
  intl: ^0.20.0
  flutter_inappwebview: ^6.1.5
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.10
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+2
  sqflite_common_ffi_web: ^1.1.1
  flutter_local_notifications: ^19.5.0
  calendar_timeline:
    git:
      url: https://github.com/muhammadtalhasultan/calendar_timeline.git
      ref: dependabot/pub/intl-0.20.2 
  easy_date_timeline: ^2.0.9
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  firebase_analytics: ^12.0.4
  loading_animation_widget: ^1.2.0+4
  shimmer: ^2.0.0
  app_settings: ^5.1.1
  flutter_dynamic_icon_plus: ^1.4.0
  in_app_review: ^2.0.6
  store_redirect: ^2.0.1
  flutter_localizations:
    sdk: flutter
  html: ^0.15.4
  purchases_flutter: ^9.10.5
  purchases_ui_flutter: ^9.10.5
  mobile_scanner: ^7.1.3
  path: any
  go_router: ^17.0.1
dev_dependencies:
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.1
  dependency_validator: ^5.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
